### ISSUE TITLE
"Login Fehlerhaft" bei Angabe korrekter Login-Daten

### ISSUE THREAD

**Issue by moonlies** [Tyde/TuCanMobile#72]
Einloggen ist nicht möglich, da die App die Login-Daten nicht akzeptiert.
TuCanMobile 0.4.2 unter Android 4.4.4 sowie 4.2.

**Comment by Tyde** [comment]
Das ist schwer zu debuggen. Ich habe leider nur Zugriff auf meine Anmeldedaten und dort funktioniert es. Kannst du mal schauen ob es möglich ist, dein Passwort zu ändern und damit eine Anmeldung funktioniert?

Außerdem: Bis zu wieviel Prozent schafft es die Anmeldung?

**Comment by moonlies** [comment]
Das Ändern des Passworts hat nichts bewirkt, nach wie vor scheitert der Loginvorgang bei 50%.

**Comment by moonlies** [comment]
Ist es möglich, dass das Problem nur bei der Fdroid Version die ich installiert habe besteht? Die Versionsnummer ist 0.4.2

**Comment by Tyde** [comment]
Tucan hat irgendwann den Login-Prozess gewechselt. Das habe ich in Version 0.4.4 gefixed. Heißt das kann es verursachen.

Die Version auf F-Droid ist nicht aktuell.

**Comment by Tyde** [comment]
Bug ist also behoben. F-Droid muss aber halt geupdatet werden.
